---
on: [push, pull_request]
name: lint-test

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install stylua
        uses: baptiste0928/cargo-install@v3
        with:
          crate: stylua
          version: '0.20.0'
          features: 'lua52'

      - name: run lint
        run: |
          stylua --color always --check lua spec

  test-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    name: test-linux
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1.5'

      - name: setup luarocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: '3.11.1'

      - name: run tests
        run: |
          sudo apt-get install -y libgit2-1.7
          sudo ln -s /usr/lib/x86_64-linux-gnu/libgit2.so.1.7 /usr/local/lib/libgit2.so
          sudo ldconfig
          nvim --version
          luarocks test --local -- --config-file=nlua.busted

  test-macos:
    runs-on: macos-14
    strategy:
      matrix:
        nvim-versions: ['stable']
    name: test-macos
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: setup Lua
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.1.5'

      - name: setup luarocks
        uses: leafo/gh-actions-luarocks@v4
        with:
          luarocksVersion: '3.11.1'

      - name: run tests
        run: |
          brew install libgit2
          nvim --version
          luarocks test --local -- --config-file=nlua.busted --output=tap
